routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();


Route::get('/', 'EntryController@index')->name('index');
Route::get('entries/{id}', 'EntryController@entriesByUser')->name('userEntries');

Route::get('/my_entries', 'UserProfileController@index')->name('home');
Route::get('profile', 'UserProfileController@profile')->name('profile');
Route::post('profile', 'UserProfileController@updateProfile')->name('update_profile');

Route::group(['middleware' => ['auth']], function () {
    Route::get('profile/retrieveTweets', 'TwitterController@retrieveTweets')->name('retrieveTweets');
    Route::get('profile/twitterCallback', 'TwitterController@callBack')->name('callbackTwitter');
});

Route::resource( 'entry_action' ,EntryActionsController::class);

app/Entry.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Entry extends Model
{

    protected $fillable = ['title', 'content'];

    public static function getEntriesPagination($id = null)
    {
        $entries = is_null($id) ? Entry::orderBy('created_at', 'desc')
                : Entry::where("user_id", $id)->orderBy('created_at', 'desc');
        return $entries->paginate(config('jobsity.pagination'));
    }

    public static function printAction(Entry $entry)
    {
        if ($entry->user_id === auth()->user()->id) {
            echo self::find($entry->id)->action_links;
        }
    }

    /**
     * Get the owner to the entry
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getDateAndUserAttribute()
    {
        return $this->created_at." by ".$this->user->url;
    }

    public function getCreatedAtAttribute($value)
    {
        return Carbon::parse($value)->rawFormat('M j, Y g:i:s A');
    }

    public function getContentAttribute($value)
    {
        return preg_replace("/\n\n/", "<br />", $value);
    }

    public function getContentPlainAttribute()
    {
        return str_replace('<br />', "\n", $this->content);
    }

    public function getDeleteLinkAttribute()
    {
        return view('entry.formDelete', ['entry' => $this]);
    }

    public function getEditLinkAttribute()
    {
        return '<div class="col-md-3"><a href="'.route("entry_action.edit",
                        ["id" => $this->id]).'">Edit Entry</a></div>';
    }

    public function getActionLinksAttribute()
    {
        return '<div class="row">'.$this->deleteLink.' '.$this->editLink.'</div>';
    }

}

app/Http/Controllers/EntryController.php
<?php

namespace App\Http\Controllers;

use App\Entry;
use App\Tweet;
use Illuminate\Http\Request;

class EntryController extends Controller
{

    public function index()
    {
        return view('entries', [
                'entries' => Entry::getEntriesPagination(),
                'tweets'  => auth()->check() ? Tweet::withoutGlobalScope('notHidden')->get() : Tweet::all(),
        ]);
    }

    public function entriesByUser($id)
    {
        return view('entries', [
                'entries' => Entry::getEntriesPagination($id),
                'tweets'  => Tweet::getUserTweets($id),
        ]);
    }
}

resources/views/entry/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-9 col-sm-3 blog-main">
                <form action="{{ route('entry_action.store') }}" method="POST">
                    @csrf

                    <div class="form-group row">
                        <label for="title" class="col-md-2 col-form-label text-md-right">{{ __('Title') }}</label>
                        <div class="col-md-10">
                            <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}" required autocomplete="name" autofocus>
                            @error('title')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="content" class="col-md-2 col-form-label text-md-right">{{ __('Content') }}</label>
                        <div class="col-md-10">
                            <textarea id="content" type="text" class="form-control textarea_big @error('content') is-invalid @enderror" name="content" required>{{ old('content') }}</textarea>
                            @error('content')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row mb-0">
                        <div class="col-md-7 offset-md-5">
                            <button type="submit" class="btn btn-primary">
                                {{ __('Create') }}
                            </button>
                            <a class="btn btn-primary"  href="{{ route('home') }}">
                                {{ __('View My Entries') }}
                            </a>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/entry/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-9 col-sm-3 blog-main">
                <form action="{{ route('entry_action.update' , ['id' => $entry->id]) }}" method="POST">
                    @method('PUT')
                    @csrf

                    <div class="form-group row">
                        <label for="title" class="col-md-2 col-form-label text-md-right">{{ __('Title') }}</label>
                        <div class="col-md-10">
                            <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') ?? $entry->title }}" required autocomplete="name" autofocus>
                            @error('title')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="content" class="col-md-2 col-form-label text-md-right">{{ __('Content') }}</label>
                        <div class="col-md-10">
                            <textarea id="content" type="text" class="form-control textarea_big @error('content') is-invalid @enderror" name="content" required>{{ old('content') ?? $entry->contentPlain }}</textarea>
                            @error('content')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row mb-0">
                        <div class="col-md-7 offset-md-5">
                            <button type="submit" class="btn btn-primary">
                                {{ __('Update') }}
                            </button>
                            <a class="btn btn-primary"  href="{{ route('home') }}">
                                {{ __('View My Entries') }}
                            </a>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/entry/formDelete.blade.php
<div class="col-md-3 ">
    <form action="{{ route('entry_action.destroy' , ['id' => $entry->id]) }}" method="POST">
        @method('DELETE')
        @csrf
        <input type="submit" onclick="return confirm('Are you sure that you want to delete this entry?')" class="btn btn-link no-padding" value="{{ __("Delete Entry") }}">

    </form>
</div>